### Import packages

In [6]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

### Import the dataset

In [2]:
df = pd.read_csv('letterdata.csv')

In [3]:
df.shape

(20000, 17)

In [4]:
df.columns

Index(['letter', 'xbox', 'ybox', 'width', 'height', 'onpix', 'xbar', 'ybar',
       'x2bar', 'y2bar', 'xybar', 'x2ybar', 'xy2bar', 'xedge', 'xedgey',
       'yedge', 'yedgex'],
      dtype='object')

### Decide the input and output variables

In [9]:
x = df.drop('letter', axis = 1)
y = df['letter']

### Label encoding of the output data

In [11]:
y

0        T
1        I
2        D
3        N
4        G
        ..
19995    D
19996    C
19997    T
19998    S
19999    A
Name: letter, Length: 20000, dtype: object

In [12]:
y.value_counts()

U    813
D    805
P    803
T    796
M    792
A    789
X    787
Y    786
N    783
Q    783
F    775
G    773
E    768
B    766
V    764
L    761
R    758
I    755
O    753
W    752
S    748
J    747
K    739
C    736
H    734
Z    734
Name: letter, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_le = le.fit_transform(y)

In [15]:
y_le

array([19,  8,  3, ..., 19, 18,  0])

### One-hot encoding

In [17]:
from keras.utils import to_categorical

In [20]:
data = [1,3,2,3,2,1,2,3,2,1,2,3,2]

In [21]:
to_categorical(data)

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)

In [22]:
y_ohe = to_categorical(y_le)

In [23]:
y_ohe

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [24]:
y_ohe.shape

(20000, 26)

### Cross validation

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y_ohe, random_state=0)

In [28]:
x_train.shape

(15000, 16)

In [30]:
x_test.shape

(5000, 16)

### Build the Neural Network Model

In [34]:
model = Sequential()

# Input layer
model.add(Dense(16, input_shape=(16,), activation='relu'))

model.add(Dense(32, activation='relu'))

model.add(Dense(64, activation='relu'))

model.add(Dense(32, activation='relu'))

# Output layer
model.add(Dense(26, activation='softmax'))

In [35]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 16)                272       
                                                                 
 dense_7 (Dense)             (None, 32)                544       
                                                                 
 dense_8 (Dense)             (None, 64)                2112      
                                                                 
 dense_9 (Dense)             (None, 32)                2080      
                                                                 
 dense_10 (Dense)            (None, 26)                858       
                                                                 
Total params: 5,866
Trainable params: 5,866
Non-trainable params: 0
_________________________________________________________________


### Compile the model

In [37]:
model.compile(loss='categorical_crossentropy', optimizer='adam',
             metrics=['accuracy'])

### Train the model

In [39]:
model.fit(x_train, y_train, epochs=50, batch_size=20)

Epoch 1/50
750/750 [==============================] - 6s 3ms/step - loss: 2.0768 - accuracy: 0.3817
Epoch 2/50
750/750 [==============================] - 2s 3ms/step - loss: 1.2369 - accuracy: 0.6292
Epoch 3/50
750/750 [==============================] - 2s 3ms/step - loss: 0.9762 - accuracy: 0.7022
Epoch 4/50
750/750 [==============================] - 2s 3ms/step - loss: 0.8231 - accuracy: 0.7495
Epoch 5/50
750/750 [==============================] - 2s 3ms/step - loss: 0.7184 - accuracy: 0.7791
Epoch 6/50
750/750 [==============================] - 2s 3ms/step - loss: 0.6441 - accuracy: 0.8008
Epoch 7/50
750/750 [==============================] - 2s 3ms/step - loss: 0.5888 - accuracy: 0.8192
Epoch 8/50
750/750 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.8280
Epoch 9/50
750/750 [==============================] - 2s 3ms/step - loss: 0.5057 - accuracy: 0.8433
Epoch 10/50
750/750 [==============================] - 2s 3ms/step - loss: 0.4693 - accuracy: 0.8523

### Evaluate the model

In [41]:
model.evaluate(x_test, y_test, batch_size=1)

5000/5000 [==============================] - 11s 2ms/step - loss: 0.2480 - accuracy: 0.9166


[0.24800285696983337, 0.9165999889373779]

### Predict on the new data

In [43]:
new = [[3,4,5,6,1,7,8,4,3,7,14,8,3,9,0,8]]

In [44]:
model.predict(new)

1/1 [==============================] - 0s 188ms/step


array([[1.1397400e-26, 0.0000000e+00, 3.7230862e-21, 2.4790852e-16,
        0.0000000e+00, 8.6764899e-16, 3.2509571e-33, 9.9949077e-27,
        5.7876398e-17, 1.2651338e-26, 2.0405788e-23, 6.1558190e-30,
        9.4995281e-25, 2.3670821e-26, 8.5528337e-23, 4.1287730e-22,
        9.3472600e-17, 0.0000000e+00, 1.7659100e-19, 2.8033253e-13,
        1.0063911e-14, 9.9971753e-01, 1.1726041e-19, 3.3818407e-18,
        2.8242261e-04, 0.0000000e+00]], dtype=float32)

In [45]:
import numpy as np

In [46]:
np.argmax(model.predict(new))

1/1 [==============================] - 0s 69ms/step


21

In [50]:
le.inverse_transform([np.argmax(model.predict(new, verbose=0))])[0]

'V'

In [57]:
new1 = [[4,4,5,5,4,7,9,4,5,7,7,8,3,7,6,6]]
new2 = [[5,9,7,7,6,5,7,1,6,9,8,10,3,8,3,8]]

In [58]:
le.inverse_transform([np.argmax(model.predict(new1, verbose=0))])[0]

'I'

In [59]:
le.inverse_transform([np.argmax(model.predict(new2, verbose=0))])[0]

'K'