In [1]:
# ANN Basic Binary Classification
# Dataset: pima-new.csv
# Location: https://mitu.co.in/dataset

### Import libraries

In [2]:
import numpy as np

### Import Dataset

In [5]:
df = np.loadtxt('pima-new.csv', delimiter=',')

In [6]:
df

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [7]:
df.shape

(768, 9)

### Separate input and output data

In [11]:
x = df[:,:8]

y = df[:,8]

In [12]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [13]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [14]:
# Count number of classes in each category
from collections import Counter
Counter(y)

Counter({1.0: 268, 0.0: 500})

### Import the Keras classes

In [16]:
from keras.models import Sequential
from keras.layers import Dense

### Create the neural network model

In [20]:
# Create the model object
model = Sequential()

# add the input layer
model.add(Dense(8, input_shape=(8,)))

# add hidden layer
model.add(Dense(16, activation='relu'))

# add output layer
model.add(Dense(1, activation='sigmoid'))

In [21]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 8)                 72        
                                                                 
 dense_4 (Dense)             (None, 16)                144       
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 233
Trainable params: 233
Non-trainable params: 0
_________________________________________________________________


### Compile the model

In [23]:
model.compile(loss='binary_crossentropy', optimizer='adam',
             metrics=['accuracy'])

### Train the model

In [26]:
model.fit(x, y, epochs=100, batch_size=10)

Epoch 1/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5455 - accuracy: 0.7292
Epoch 2/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5670 - accuracy: 0.7253
Epoch 3/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5423 - accuracy: 0.7526
Epoch 4/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5638 - accuracy: 0.7240
Epoch 5/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5620 - accuracy: 0.7253
Epoch 6/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5394 - accuracy: 0.7448
Epoch 7/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5589 - accuracy: 0.7409
Epoch 8/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5574 - accuracy: 0.7422
Epoch 9/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5411 - accuracy: 0.7370
Epoch 10/100
77/77 [==============================] - 0s 3ms/step - loss: 0.5349 - accuracy: 0.7409
Epoch 11/

77/77 [==============================] - 0s 2ms/step - loss: 0.5084 - accuracy: 0.7578
Epoch 84/100
77/77 [==============================] - 0s 2ms/step - loss: 0.5071 - accuracy: 0.7591
Epoch 85/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4831 - accuracy: 0.7721
Epoch 86/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4981 - accuracy: 0.7656
Epoch 87/100
77/77 [==============================] - 0s 2ms/step - loss: 0.5001 - accuracy: 0.7578
Epoch 88/100
77/77 [==============================] - 0s 2ms/step - loss: 0.5077 - accuracy: 0.7565
Epoch 89/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4869 - accuracy: 0.7760
Epoch 90/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4867 - accuracy: 0.7839
Epoch 91/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4841 - accuracy: 0.7799
Epoch 92/100
77/77 [==============================] - 0s 2ms/step - loss: 0.5012 - accuracy: 0.7552
Epoch 93/100


### Evaluate the performance

In [29]:
model.evaluate(x, y, batch_size=10)

77/77 [==============================] - 0s 2ms/step - loss: 0.5107 - accuracy: 0.7656


[0.5106652975082397, 0.765625]

### Perform the prediction on usneen data

In [33]:
new = [[13, 145, 82, 19, 110, 22.2, 0.245, 57]]

In [36]:
model.predict(new)[0][0]

1/1 [==============================] - 0s 54ms/step


0.35950398

In [37]:
new2 = [[11, 143, 94, 33, 146, 36.6, 0.254, 51]]
model.predict(new2, verbose=False)[0][0]

0.7281936