In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
x = np.array([2,14,25,37,44,51,78,99])
y = np.array([18,23,34,38,49,67,71,82])
z = np.array([67,61,54,42,31,21,19,16])
p = np.array([56,51,58,43,57,50,49,41])

In [6]:
# pearson correlation
np.corrcoef(x, y)

array([[1.        , 0.96533714],
       [0.96533714, 1.        ]])

In [7]:
np.corrcoef(x, z)

array([[ 1.        , -0.92856819],
       [-0.92856819,  1.        ]])

In [9]:
np.corrcoef(x, p)

array([[ 1.        , -0.64071012],
       [-0.64071012,  1.        ]])

In [10]:
import pandas as pd
df = pd.DataFrame({
    'x':x,
    'y':y,
    'z':z,
    'p':p
})

In [12]:
df.corr()

x         y         z         p
x  1.000000  0.965337 -0.928568 -0.640710
y  0.965337  1.000000 -0.975902 -0.547668
z -0.928568 -0.975902  1.000000  0.520457
p -0.640710 -0.547668  0.520457  1.000000

In [13]:
df.corr(method='spearman')

x         y         z         p
x  1.000000  1.000000 -1.000000 -0.619048
y  1.000000  1.000000 -1.000000 -0.619048
z -1.000000 -1.000000  1.000000  0.619048
p -0.619048 -0.619048  0.619048  1.000000

In [14]:
sal = pd.read_csv('Salary_Data.csv')
sal.corr()

YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [15]:
cars = pd.read_csv('mtcars.csv')
cars.corr()

mpg       cyl      disp        hp      drat        wt      qsec  \
mpg   1.000000 -0.852162 -0.847551 -0.776168  0.681172 -0.867659  0.418684   
cyl  -0.852162  1.000000  0.902033  0.832447 -0.699938  0.782496 -0.591242   
disp -0.847551  0.902033  1.000000  0.790949 -0.710214  0.887980 -0.433698   
hp   -0.776168  0.832447  0.790949  1.000000 -0.448759  0.658748 -0.708223   
drat  0.681172 -0.699938 -0.710214 -0.448759  1.000000 -0.712441  0.091205   
wt   -0.867659  0.782496  0.887980  0.658748 -0.712441  1.000000 -0.174716   
qsec  0.418684 -0.591242 -0.433698 -0.708223  0.091205 -0.174716  1.000000   
vs    0.664039 -0.810812 -0.710416 -0.723097  0.440278 -0.554916  0.744535   
am    0.599832 -0.522607 -0.591227 -0.243204  0.712711 -0.692495 -0.229861   
gear  0.480285 -0.492687 -0.555569 -0.125704  0.699610 -0.583287 -0.212682   
carb -0.550925  0.526988  0.394977  0.749812 -0.090790  0.427606 -0.656249   

            vs        am      gear      carb  
mpg   0.664039  0.599832  0.480285 -0.550925  
cyl  -0.810812 -0.522607 -0.492687  0.526988  
disp -0.710416 -0.591227 -0.555569  0.394977  
hp   -0.723097 -0.243204 -0.125704  0.749812  
drat  0.440278  0.712711  0.699610 -0.090790  
wt   -0.554916 -0.692495 -0.583287  0.427606  
qsec  0.744535 -0.229861 -0.212682 -0.656249  
vs    1.000000  0.168345  0.206023 -0.569607  
am    0.168345  1.000000  0.794059  0.057534  
gear  0.206023  0.794059  1.000000  0.274073  
carb -0.569607  0.057534  0.274073  1.000000